# Generated by Django 5.1.1 on 2024-09-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='TCGENDER',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', help_text='Хүйс', max_length=1),
        ),
    ]
