# Generated by Django 5.1.1 on 2024-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_users_tcgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='TCGENDER',
            field=models.CharField(choices=[('M', 'ЭР'), ('F', 'ЭМ')], default='M', help_text='Хүйс', max_length=1),
        ),
    ]
