# Generated by Django 5.1.1 on 2024-09-07 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_users_tcgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.DecimalField(decimal_places=0, max_digits=20, unique=True)),
                ('itemName', models.CharField(max_length=255)),
                ('itemBillName', models.CharField(max_length=255)),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('isActive', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorId', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('isMain', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('isIncome', models.BooleanField(default=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('UserPk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.users')),
                ('infoSector', models.ForeignKey(limit_choices_to={'is_main': True}, on_delete=django.db.models.deletion.CASCADE, to='delivery.infosector')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.history')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.infoproduct')),
            ],
        ),
    ]
