# Generated by Django 5.1.1 on 2024-09-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_infoproduct_infosector_history_historyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='infoSector',
            field=models.ForeignKey(limit_choices_to={'isMain': True}, on_delete=django.db.models.deletion.CASCADE, to='delivery.infosector'),
        ),
    ]
