# Generated by Django 5.1.1 on 2024-09-07 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_history_infosector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='infoSector',
        ),
        migrations.AddField(
            model_name='history',
            name='infoOutSector',
            field=models.ForeignKey(default=1, limit_choices_to={'isMain': True}, on_delete=django.db.models.deletion.CASCADE, related_name='out_sector_histories', to='delivery.infosector'),
        ),
        migrations.AddField(
            model_name='history',
            name='infoToSector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_sector_histories', to='delivery.infosector'),
        ),
    ]
