# Generated by Django 5.1.1 on 2024-09-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_history_infosector_history_infooutsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
